#ifndef __KEYCODES_H__
#define __KEYCODES_H__
#include "ctype.h"
//the values assigned to each come from USB Usage Table 
//some fields are missing, but likely wont use them for now
#define KEY_RESERVED            0x00
#define KEY_ERR_ROLLOVER        0x01
#define KEY_POST_FAIL           0x02
#define KEY_ERR_UNDEFINED       0x03
#define KEY_A                   0x04
#define KEY_B                   0x05
#define KEY_C                   0x06
#define KEY_D                   0x07
#define KEY_E                   0x08
#define KEY_F                   0x09
#define KEY_G                   0x0A
#define KEY_H                   0x0B
#define KEY_I                   0x0C
#define KEY_J                   0x0D
#define KEY_K                   0x0E
#define KEY_L                   0x0F
#define KEY_M                   0x10
#define KEY_N                   0x11
#define KEY_O                   0x12
#define KEY_P                   0x13
#define KEY_Q                   0x14
#define KEY_R                   0x15
#define KEY_S                   0x16
#define KEY_T                   0x17
#define KEY_U                   0x18
#define KEY_V                   0x19
#define KEY_W                   0x1A
#define KEY_X                   0x1B
#define KEY_Y                   0x1C
#define KEY_Z                   0x1D
#define KEY_1_AND_EXCLAMATION   0x1E
#define KEY_2_AND_AT            0x1F
#define KEY_3_AND_HASH          0x20
#define KEY_4_AND_DOLLAR        0x21
#define KEY_5_AND_PERCENT       0x22
#define KEY_6_AND_CARET         0x23
#define KEY_7_AND_AMPERSAND     0x24
#define KEY_8_AND_ASTERISK      0x25
#define KEY_9_AND_LEFT_PAREN    0x26
#define KEY_0_AND_RIGHT_PAREN   0x27
#define KEY_RETURN_ENTER        0x28
#define KEY_ESCAPE              0x29
#define KEY_DELETE_BACKSPACE    0x2A
#define KEY_TAB                 0x2B
#define KEY_SPACEBAR            0x2C
#define KEY_MINUS_UNDERSCORE    0x2D
#define KEY_EQUAL_PLUS          0x2E
#define KEY_LEFT_BRACKET        0x2F
#define KEY_RIGHT_BRACKET       0x30
#define KEY_BACKSLASH_AND_PIPE  0x31
#define KEY_NON_US_HASH_TILDE   0x32
#define KEY_SEMICOLON_COLON     0x33
#define KEY_APOSTROPHE_QUOTE    0x34
#define KEY_GRAVE_ACCENT_TILDE  0x35
#define KEY_COMMA_LESS_THAN     0x36
#define KEY_PERIOD_GREATER_THAN 0x37
#define KEY_SLASH_QUESTION      0x38
#define KEY_CAPS_LOCK           0x39
#define KEY_F1                  0x3A
#define KEY_F2                  0x3B
#define KEY_F3                  0x3C
#define KEY_F4                  0x3D
#define KEY_F5                  0x3E
#define KEY_F6                  0x3F
#define KEY_F7                  0x40
#define KEY_F8                  0x41
#define KEY_F9                  0x42
#define KEY_F10                 0x43
#define KEY_F11                 0x44
#define KEY_F12                 0x45
#define KEY_PRINT_SCREEN        0x46
#define KEY_SCROLL_LOCK         0x47
#define KEY_PAUSE               0x48
#define KEY_INSERT              0x49
#define KEY_HOME                0x4A
#define KEY_PAGE_UP             0x4B
#define KEY_DELETE_FORWARD      0x4C
#define KEY_END                 0x4D
#define KEY_PAGE_DOWN           0x4E
#define KEY_RIGHT_ARROW         0x4F
#define KEY_LEFT_ARROW          0x50
#define KEY_DOWN_ARROW          0x51
#define KEY_UP_ARROW            0x52
#define KEY_NUM_LOCK_AND_CLEAR  0x53
#define KEY_KEYPAD_SLASH        0x54
#define KEY_KEYPAD_ASTERISK     0x55
#define KEY_KEYPAD_MINUS        0x56
#define KEY_KEYPAD_PLUS         0x57
#define KEY_KEYPAD_ENTER        0x58
#define KEY_KEYPAD_1_AND_END    0x59
#define KEY_KEYPAD_2_AND_DOWN_ARROW     0x5A
#define KEY_KEYPAD_3_AND_PAGE_DOWN      0x5B
#define KEY_KEYPAD_4_AND_LEFT_ARROW     0x5C
#define KEY_KEYPAD_5            0x5D
#define KEY_KEYPAD_6_AND_RIGHT_ARROW    0x5E
#define KEY_KEYPAD_7_AND_HOME   0x5F
#define KEY_KEYPAD_8_AND_UP_ARROW       0x60
#define KEY_KEYPAD_9_AND_PAGE_UP        0x61
#define KEY_KEYPAD_0_AND_INSERT         0x62
#define KEY_KEYPAD_DECIMAL      0x63
#define KEY_KEYPAD_EQUAL_SIGN   0x67
#define KEY_L_CTRL            0xE0
#define KEY_L_SHIFT              0xE1
#define KEY_L_ALT                0xE2
#define KEY_L_GUI          0xE3
#define KEY_R_CTRL           0xE4
#define KEY_R_SHIFT             0xE5
#define KEY_R_ALT               0xE6
#define KEY_R_GUI         0xE7
#define KEY_RESERVED_DV                    0xE8

extern const char* modified_printable_keycode_mappings[];
extern const char *base_printable_keycode_mappings[];
#endif /*KEYCODES_H__*/
